export const GET_DRIVERS = 'GET_DRIVERS'
export const GET_DETAIL = "GET_DETAIL";
export const CLEAN_DETAIL = "CLEAN_DETAIL";
export const GET_DRIVERS_BY_NAME = 'GET_DRIVERS_BY_NAME'
export const GET_DRIVER_BY_ID = 'GET_DRIVER_BY_ID'
export const CLEAN_DRIVERS = 'CLEAN_DRIVERS'